application: pubmedbrain
version: 1
runtime: python
api_version: 1

handlers:

- url: /remote_api 
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py 
  login: admin
  
- url: /css
  static_dir: css

- url: /script
  static_dir: script

- url: /images
  static_dir: images

- url: /documents
  static_dir: documents

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
    
- url: /Jit
  static_dir: Jit

- url: /admin/.*
  script: main.py
  login: admin

- url: /tasks/.*
  script: main.py
  login: admin
  
- url: .*
  script: main.py

builtins:
- remote_api: on
- datastore_admin: on