# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('synonyms', models.TextField()),
                ('acronyms', models.TextField())
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('conjunction', models.IntegerField()),
                ('a_not_b', models.IntegerField()),
                ('b_not_a', models.IntegerField()),
                ('disjunction', models.IntegerField()),
                ('prob_association', models.FloatField()),
                ('term_keys', models.TextField())
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('color_highlight', models.CharField(max_length=255)),
                ('description', models.TextField())
           ],
        )
    ]
